version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/system"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/updater"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/image-factory"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
