version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/image-factory"
    schedule:
      interval: "daily"
    target-branch: "development"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/installer-factory"
    schedule:
      interval: "daily"
    target-branch: "development"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/system"
    schedule:
      interval: "daily"
    target-branch: "development"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/system-raspberry"
    schedule:
      interval: "daily"
    target-branch: "development"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/updater"
    schedule:
      interval: "daily"
    target-branch: "development"
    assignees:
      - "simonwalz"
