FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV container=docker

ENTRYPOINT ["sh", "-c", "rm -f /.dockerenv; trap 'echo Received SIGTERM; exit 0' TERM; sleep infinity & wait"]

COPY seccomp-default.json /etc/docker/

# Install required packages
RUN apt-get update && apt-get install --no-install-recommends -y \
  ## cuos system dependencies (lxc) \
  busybox-static \
  ## cuos os dependencies \
  #-btrfs-progs \
  dbus \
  dbus-broker \
  docker-cli \
  docker.io \
  #-kbd \
  kmod \
  lsb-release \
  #-selinux-policy-default \
  systemd \
  systemd-sysv \
  #-systemd-timesyncd \
  ## network dependencies \
  hostname \
  ifupdown \
  iproute2 \
  iptables \
  isc-dhcp-client \
  isc-dhcp-common \
  openresolv \
  ## cuos service dependencies \
  ca-certificates \
  cloud-guest-utils \
  curl \
  dialog \
  gnupg2 \
  inetutils-ping \
  jq \
  jsonschema-jv \
  less \
  pass \
  sudo \
  yq \
  ## debugging tools \
  openssh-server \
  vim \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  # No timesyncd for LXC \
  && systemctl disable ssh.socket ssh.service sshd.service \
  && systemctl mask ssh.socket \
  && echo "Port 4222\nPermitRootLogin yes" >/etc/ssh/sshd_config.d/cuos.conf \
  && rm -f /etc/ssh/ssh_host_* \
  && echo "net.ipv4.ip_forward=1" >>/etc/sysctl.conf \
  ## Ensure persistence \
  && mkdir -p /data \
  && rm -f /etc/machine-id && ln -sf /data/machine-id /etc/machine-id \
  && rm -Rf /var/log && ln -sf /data/log /var/log \
  && rm -Rf /var/lib/dhcp && ln -sf /data/dhcp /var/lib/dhcp \
  && rm -Rf /var/lib/docker && ln -sf /data/docker /var/lib/docker \
  && rm -Rf /var/lib/containerd && ln -sf /data/containerd /var/lib/containerd \
  && rm -Rf /root && ln -sf /data/root /root \
  && echo "[Journal]\nStorage=persistent\nSystemMaxUse=1G\nRuntimeMaxUse=50M\nCompress=yes\nSeal=yes\nSplitMode=uid\nSyncIntervalSec=5m\nRateLimitInterval=30s\nRateLimitBurst=1000" >/etc/systemd/journald.conf \
  && rm /etc/network/interfaces \
  ## LXC \
  && systemctl mask cgroupfs-mount.service sys-kernel-debug.mount

# Install CuOS scripts (systemd required)
COPY cuos/ /usr/local/cuos/
RUN /usr/local/cuos/install.sh
