FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV container=docker

ENTRYPOINT ["sh", "-c", "rm -f /.dockerenv; trap 'echo Received SIGTERM; exit 0' TERM; sleep infinity & wait"]

COPY seccomp-default.json /etc/docker/

# Install required packages
RUN apt-get update && apt-get install --no-install-recommends -y \
  busybox-static \
  ca-certificates \
  curl \
  dbus \
  dbus-broker \
  docker-cli \
  docker.io \
  gnupg2 \
  jq \
  kmod \
  openssh-server \
  pass \
  systemd \
  systemd-sysv \
  vim \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install CuOS scripts (systemd required)
COPY cuos/ /usr/local/cuos/
RUN /usr/local/cuos/install.sh

RUN apt-get update && apt-get install --no-install-recommends -y \
  hostname \
  ifupdown \
  iproute2 \
  iptables \
  isc-dhcp-client \
  isc-dhcp-common \
  openresolv \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  && echo "net.ipv4.ip_forward=1" >>/etc/sysctl.conf

# Put logs in /data/logs
RUN  mkdir -p /data && \
  rm -f /etc/machine-id && ln -sf /data/machine-id /etc/machine-id && \
  rm -Rf /var/log && ln -sf /data/log /var/log && \
  rm -Rf /var/lib/dhcp && ln -sf /data/dhcp /var/lib/dhcp && \
  rm -Rf /var/lib/docker && mkdir -p /data/docker && ln -sf /data/docker /var/lib/docker && \
  rm -Rf /var/lib/containerd && mkdir -p /data/containerd && ln -sf /data/containerd /var/lib/containerd && \
  rm -Rf /root/.docker && mkdir -p /data/.docker && ln -sf /data/.docker /root/.docker && \
  echo "[Journal]\nStorage=persistent\nSystemMaxUse=1G\nRuntimeMaxUse=50M\nCompress=yes\nSeal=yes\nSplitMode=uid\nSyncIntervalSec=5m\nRateLimitInterval=30s\nRateLimitBurst=1000" >/etc/systemd/journald.conf && \
  rm /etc/network/interfaces && \
  mkdir -p /data/shieldor && \
  ln -sf /data/shieldor /usr/local/shieldor && \
  rm -f /etc/ssh/ssh_host_* && \
  systemctl mask cgroupfs-mount.service sys-kernel-debug.mount

# Set up SSH
RUN echo 'root:root' | chpasswd && \
  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

